### ISSUE TITLE
Git master doesn't build

### ISSUE THREAD

**Issue by prokoudine** [timowest/rogue#45]
./presetgen.py  
Traceback (most recent call last):
  File "./presetgen.py", line 120, in <module>
    main()
  File "./presetgen.py", line 113, in main
    dcf(1, {"type": 2}))
  File "./presetgen.py", line 86, in preset
    ttlFile = open("presets/" +name+".ttl", "w")
IOError: [Errno 2] No such file or directory: 'presets/test.ttl'
make: **\* [presets.ttl] Error 1

Forgot pushing a few files? ;-)

**Comment by timowest** [comment]
Just a glitch in the makefile. Should be fixed now.

rogue is still in alpha stage, and I am currently refactoring the UI from Gtk to Qt.
