### ISSUE TITLE
GUI link error at instantiate

### ISSUE THREAD

**Issue by harryhaaren** [timowest/rogue#77]
After a make, make install, lv2ls lists the synth properly, Jalv fails to instantiate UI: linker flags error?

suil error: Unable to open UI library /usr/local/lib/lv2/lv2-rogue.lv2/rogue-gui.so (/usr/local/lib/lv2/lv2-rogue.lv2/rogue-gui.so: undefined symbol: _ZTV8rogueGUI)

make VERBOSE=1 gives:
g++ -fPIC -DPIC -std=c++11  -g -shared dsp/*.cpp src/gui/rogue-gui.cpp `pkg-config --cflags --libs QtGui`  `pkg-config --cflags --libs lvtk-plugin-1` `pkg-config --cflags --libs lvtk-ui-1` -lfftw3f -Idsp -Isrc -o rogue-gui.so

**Comment by timowest** [comment]
Is this related to https://github.com/timowest/rogue/issues/77 ?

Also does the following work?

 make gui
./qttest.out

**Comment by harryhaaren** [comment]
output:
make gui
g++ -g -std=c++11 src/gui/test.cpp `pkg-config --cflags --libs QtGui`  `pkg-config --cflags --libs lvtk-ui-1` -lfftw3f -Idsp -Isrc -o qttest.out 
/tmp/cc9W4OL8.o: In function `rogueGUI::rogueGUI(char const*)':
/root/programming/rogue/src/gui/rogue-gui.cpp:812: undefined reference to`vtable for rogueGUI'
/tmp/cc9W4OL8.o: In function `rogueGUI::~rogueGUI()':
/root/programming/rogue/src/gui/rogue-gui.cpp:912: undefined reference to`vtable for rogueGUI'
collect2: error: ld returned 1 exit status
make: **\* [gui] Error 1

**Comment by harryhaaren** [comment]
After fixing https://github.com/timowest/rogue/issues/78, it now loads OK
