### ISSUE TITLE
/bin/sh: moc: command not found

### ISSUE THREAD

**Issue by harryhaaren** [timowest/rogue#78]
When doing 
make -B
for a full recompile, the following error occurs:

moc src/gui/rogue-gui.cpp > src/gui/rogue-gui.mcpp
/bin/sh: moc: command not found
make: **\* [src/gui/rogue-gui.mcpp] Error 127

Running "make" without -B afterwards seems to compile fine.
I'm not familiar with moc, but I presume its some sort of pre-compiler / generator. I have bison (yacc) installed.

**Comment by timowest** [comment]
moc comes bundled with Qt 4.*

You need to have Qt 4.\* dependencies installed (qt4-dev-tools etc on  Ubuntu)

**Comment by harryhaaren** [comment]
I have "moc-qt4" : there's a big change in naming / libraries from qt to qt4 AFAIK (not a QT dev myself).
Updating the Makefile to moc-qt4 fixes. Close issue if you wish

**Comment by timowest** [comment]
Ok, locally both seem to point to the same, but maybe moc-qt4 will be more explicit.

tiwe@tiwe-t430:~/work/workspace/rogue$ moc -v
Qt Meta Object Compiler version 63 (Qt 4.8.4)

tiwe@tiwe-t430:~/work/workspace/rogue$ moc-qt4 -v
Qt Meta Object Compiler version 63 (Qt 4.8.4)
